### ISSUE TITLE
Segmentation.m fails when .hdr image is not square

### ISSUE THREAD

**Issue by arnodelorme** [sccn/NFT#1]
Thansfered from Bugzilla https://sccn.ucsd.edu/bugzilla/show_bug.cgi?id=1213

Segmentation.m fails when .hdr image is not square.
Problem arises in lines 950-952 of Segmentation.m file (NFT 2.1 / mfiles):

   for i = 1:M
      filt_im(:,:,i) = rot90(filt_im(:,:,i),3);
   end

It would be solved changing this section by:

   FI = [];
   for i = 1:M
      %filt_im(:,:,i) = rot90(filt_im(:,:,i),3);
       FI(:,:,i) = rot90(filt_im(:,:,i),3);
   end
   filt_im = FI;

**Comment by zakalinacar** [comment]
The images should come from freesurfer which always returns square images. There is now a check for square images that prevents these errors, asking the user to preprocess the MR image through freesurfer.
