### ISSUE TITLE
DFT gui screen size problem (NFT instead??)

### ISSUE THREAD

**Issue by nucleuscub** [sccn/NFT#2]
**Issue transferred from Bugzilla (Bug 982)**

**[reply] [−]DescriptionPatricia Walshaw 2010-11-21 10:50:00 PST**
Hi guys.  This was a problem I encountered at the 12th EEGLAB workshop that I discussed with a few of you (e.g. Julie, Zeynep).  I am working on a MacAir and when I load the DFT program, specifically the 'Image Segmentation' part, the gui truncates itself so that it is missing part of the right side (i.e. I can't see anything right of the 'Run' button - e.g. the "Next" button and things above it).  We discussed it and rather than purchasing a new computer (haha), it would be awesome if the gui was able to be resized.  This problem also happened with a new macbook at the workshop that had a smaller screen dimension.  That macbook also was running Matlab 2010b, so we determined that it wasn't the version of Matlab that was causing this problem.

**[reply] [−]Comment 1 Ramon Martinez-Cancino 2016-05-18 11:39:13 PDT**
Hi Zeynep,  Do you know if this issue was fixed??  Thanks,  Ramon

**[reply] [−]Comment 2 Ramon Martinez-Cancino 2019-12-10 11:35:07 PST**
Is this referencing NFT instead?
--

**Comment by zakalinacar** [comment]
These issues should be resolved with the latest update.
